name: Package Manager Continuous Intergration

on:
    push:
        branches: ["**"]
        tags: ["**"]
        pull_request:
            branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt-get install -y cmake python3 ccache libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev xvfb
            - name: Run run_test.py
              run: xvfb-run --auto-servernum python3 tests/run_test.py -t 5
