name: Continuous Intergration

on: [push, pull_request]

jobs:
    test:
        name: Testing on ${{ matrix.os }}.
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.9"
            - name: Run run_tests.py
              run: python tests/run_tests.py

    merge:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Merge main -> v3
              uses: devmasx/merge-branch@1.4.0
              with:
                  type: now
                  from_branch: main
                  target_branch: v3
                  github_token: ${{ github.token }}
