name: Continuous Intergration

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake python3 ccache libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev libudev-dev
            - name: Run run_test.py
              run: python3 tests/run_test.py

    merge:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Merge main -> v1
              uses: devmasx/merge-branch@1.4.0
              with:
                  type: now
                  from_branch: main
                  target_branch: v1
                  github_token: ${{ github.token }}
