name: Continuous Intergration

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake python3 ccache libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev xvfb
            - name: Run run_test.py
              run: xvfb-run --auto-servernum python3 tests/run_test.py -t 5

    merge-and-purge:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Merge main -> v1
              uses: devmasx/merge-branch@1.4.0
              with:
                  type: now
                  from_branch: main
                  target_branch: v1
                  github_token: ${{ github.token }}
            - name: Purge jsdelivr cdn cache
              run: |
                  curl https://purge.jsdelivr.net/gh/${{ github.repository_owner }}/yacpm@vv1/yacpm.cmake
                  curl https://purge.jsdelivr.net/gh/${{ github.repository_owner }}/yacpm@vv1/yacpm_extended.cmake
                  curl https://purge.jsdelivr.net/gh/${{ github.repository_owner }}/yacpm@vv1/yacpm.py
